name: Capstone Infrastructure Deployment

on:
  pull_request:
    paths:
      - "aws-infrastructure/**"
      - ".github/workflows/infrastructure-deployment.yml"

  push:
    branches:
      - main
    paths:
      - "aws-infrastructure/**"
      - ".github/workflows/infrastructure-deployment.yml"

  workflow_dispatch:
    branches:
      - main
    inputs:
      ecs_desired_task:
        description: "Number of ECS tasks to run"
        required: true
        type: number
        default: 0

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-southeast-1
  TF_WORKING_DIR: aws-infrastructure

# Infrastructure Deployment Jobs
jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::249899229305:role/github-actions-infrastructure-deployment-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Format Check
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}

        # HashiCorp support the saved plan (terraform plan -out=...) can be passed to terraform apply
        run: terraform plan -out=tfplan

  terraform-apply:
    name: Terraform Apply
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment:
      name: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::249899229305:role/github-actions-infrastructure-deployment-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform apply \
            -auto-approve \
            -var="ecs_desired_task=${{ inputs.ecs_desired_task || 0 }}"